spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productcategory
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect